hospital/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path, reverse_lazy
from django.views import defaults as default_views, generic as generic_views

from . import views as hospital_views


urlpatterns = [
    # auth
    path(route='accounts/', view=include('django.contrib.auth.urls')),
    path(route='accounts/profile/', view=hospital_views.profile.get_profile, name='profile'),

    # common
    path(route='{url}/'.format(url=settings.ADMIN_URL), view=admin.site.urls),
    path(route='', view=generic_views.RedirectView.as_view(pattern_name='history_and_form'), name='index'),
    path(route='i18n/', view=include('django.conf.urls.i18n')),
    path(route='history_and_form/', view=hospital_views.history_and_form.manage_view, name='history_and_form'),

    # session settings
    path(route='accounts/session/', view=hospital_views.session_settings.update_session_data, name='update_data'),

    # NOT USED VIEWS AND URLS
    # path(route='', view=hospital_views.home.HomeView.as_view(), name='index'),
    #
    # # parameters views
    # path(route='parameters_set/', view=hospital_views.parameters.manage_parameters, name='parameter-set'),
    # path(route='parameters/', view=hospital_views.parameters.ParameterList.as_view(), name='parameter-list'),
    # path(route='parameters/create/', view=hospital_views.parameters.ParameterCreate.as_view(), name='parameter-create'),
    # path(route='parameters/<uuid:pk>/update/', view=hospital_views.parameters.ParameterUpdate.as_view(), name='parameter-update'),
    # path(route='parameters/<uuid:pk>/delete/', view=hospital_views.parameters.ParameterDelete.as_view(), name='parameter-delete'),
    #
    # # patients views
    # path(route='patients_set/', view=hospital_views.patients.manage_patients, name='patient-set'),
    # path(route='patients/', view=hospital_views.patients.PatientList.as_view(), name='patient-list'),
    path(route='patients/create/', view=hospital_views.patients.PatientCreate.as_view(), name='patient-create'),
    # path(route='patients/<uuid:pk>/update/', view=hospital_views.patients.PatientUpdate.as_view(), name='patient-update'),
    # path(route='patients/<uuid:pk>/delete/', view=hospital_views.patients.PatientDelete.as_view(), name='patient-delete'),
    #
    # # projects views
    # path(route='projects_set/', view=hospital_views.projects.manage_projects, name='project-set'),
    # path(route='projects/', view=hospital_views.projects.ProjectList.as_view(), name='project-list'),
    # path(route='projects/create/', view=hospital_views.projects.ProjectCreate.as_view(), name='project-create'),
    # path(route='projects/<uuid:pk>/update/', view=hospital_views.projects.ProjectUpdate.as_view(),
    #      name='project-update'),
    # path(route='projects/<uuid:pk>/delete/', view=hospital_views.projects.ProjectDelete.as_view(),
    #      name='project-delete'),
    #
    # # forms views
    # path(route='forms_set/', view=hospital_views.forms.manage_forms, name='form-set'),
    # path(route='forms/', view=hospital_views.forms.FormList.as_view(), name='form-list'),
    # path(route='forms/create/', view=hospital_views.forms.FormCreate.as_view(), name='form-create'),
    # path(route='forms/<uuid:pk>/update/', view=hospital_views.forms.FormUpdate.as_view(),
    #      name='form-update'),
    # path(route='forms/<uuid:pk>/delete/', view=hospital_views.forms.FormDelete.as_view(),
    #      name='form-delete'),
    #
    # # applications views
    # path(route='applications_set/', view=hospital_views.applications.manage_applications, name='application-set'),
    # path(route='applications/', view=hospital_views.applications.ApplicationList.as_view(), name='application-list'),
    # path(route='applications/create/', view=hospital_views.applications.ApplicationCreate.as_view(), name='application-create'),
    # path(route='applications/<uuid:pk>/update/', view=hospital_views.applications.ApplicationUpdate.as_view(),
    #      name='application-update'),
    # path(route='applications/<uuid:pk>/delete/', view=hospital_views.applications.ApplicationDelete.as_view(),
    #      name='application-delete'),
]

handler403 = 'hospital.views.errors.permission_denied'

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar  # pylint:disable=import-error

        urlpatterns += [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ]

hospital/models.py
import ast
from collections import defaultdict
import datetime
import logging
import uuid

from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.core.exceptions import ValidationError
from django.utils.translation import pgettext, pgettext_lazy

from djongo import models
from djongo.models import json

from . import utils

logger = logging.getLogger(__name__)

CODE_MAX_LENGTH = 10


class AbstractTimestampModel(models.Model):
    _id = models.UUIDField(primary_key=True, default=uuid.uuid4, verbose_name=pgettext_lazy('model_field', 'ID'), editable=False)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=pgettext_lazy('model_field', 'Added'))
    updated_at = models.DateTimeField(auto_now=True, verbose_name=pgettext_lazy('model_field', 'Updated'))

    @property
    def id(self):
        return self._id

    class Meta:
        abstract = True


class User(AbstractTimestampModel, AbstractUser):

    class Meta:
        verbose_name = pgettext_lazy('model_name', 'User')
        verbose_name_plural = pgettext_lazy('model_name', 'Users')


class Patient(AbstractTimestampModel):
    full_name = models.CharField(max_length=100, verbose_name=pgettext_lazy('model_field', 'Full Name'))
    birthday = models.DateField(verbose_name=pgettext_lazy('model_field', 'Birthday'))

    class Meta:
        verbose_name = pgettext_lazy('model_name', 'Patient')
        verbose_name_plural = pgettext_lazy('model_name', 'Patients')

    def __str__(self):
        return self.full_name


class Parameter(AbstractTimestampModel):

    PARAMETER_TYPE_INTEGER = 1
    PARAMETER_TYPE_DECIMAL = 2
    PARAMETER_TYPE_STRING = 3
    PARAMETER_TYPE_MULTISTRING = 4
    PARAMETER_TYPE_BOOLEAN = 5
    PARAMETER_TYPE_DATE = 6
    PARAMETER_TYPE_DATETIME = 7
    PARAMETER_TYPE_SELECT = 8
    PARAMETER_TYPE_SELECT_MULTIPLE = 9
    PARAMETER_TYPES = (
        (PARAMETER_TYPE_INTEGER, pgettext_lazy('field_type', 'Integer')),
        (PARAMETER_TYPE_STRING, pgettext_lazy('field_type', 'String')),
        (PARAMETER_TYPE_DECIMAL, pgettext_lazy('field_type', 'Decimal')),
        (PARAMETER_TYPE_MULTISTRING, pgettext_lazy('field_type', 'Multistring')),
        (PARAMETER_TYPE_BOOLEAN, pgettext_lazy('field_type', 'Boolean')),
        (PARAMETER_TYPE_DATE, pgettext_lazy('field_type', 'Date')),
        (PARAMETER_TYPE_DATETIME, pgettext_lazy('field_type', 'Datetime')),
        (PARAMETER_TYPE_SELECT, pgettext_lazy('field_type', 'Select')),
        (PARAMETER_TYPE_SELECT_MULTIPLE, pgettext_lazy('field_type', 'Select Multiple')),
    )

    REQUIRED = (
        PARAMETER_TYPE_INTEGER,
        PARAMETER_TYPE_DECIMAL,
        PARAMETER_TYPE_STRING,
        PARAMETER_TYPE_MULTISTRING,
        PARAMETER_TYPE_BOOLEAN,
        PARAMETER_TYPE_DATE,
        PARAMETER_TYPE_DATETIME,
        PARAMETER_TYPE_SELECT,
        PARAMETER_TYPE_SELECT_MULTIPLE,
    )
    CHOICES = (
        PARAMETER_TYPE_SELECT,
        PARAMETER_TYPE_SELECT_MULTIPLE,
    )

    name = models.CharField(max_length=30, verbose_name=pgettext_lazy('model_field', 'Name'))
    description = models.TextField(verbose_name=pgettext_lazy('model_field', 'Description'))
    field_type = models.IntegerField(choices=PARAMETER_TYPES, verbose_name=pgettext_lazy('model_field', 'Type'))
    extra_params = json.JSONField(default=dict, verbose_name=pgettext_lazy('model_field', 'Extra Parameters'), blank=True)

    class Meta:
        verbose_name = pgettext_lazy('model_name', 'Parameter')
        verbose_name_plural = pgettext_lazy('model_name', 'Parameters')

    def __str__(self):
        return self.name

    def clean(self):
        super().clean()
        available = []
        errors = defaultdict(list)
        if self.field_type in self.REQUIRED:
            required = self.extra_params.get('required', False)
            available.append('required')
            if not isinstance(required, bool):
                errors['extra_params'].append(pgettext('error_msg', 'Field `required` should be boolean'))
            self.extra_params['required'] = required
        if self.field_type in self.CHOICES:
            available.extend(['choices', 'search_support'])
            search = self.extra_params.get('search_support', False)
            choices = self.extra_params.get('choices', [])
            if not isinstance(search, bool):
                errors['extra_params'].append(pgettext('error_msg', 'Field `search_support` should be boolean'))
            if not isinstance(choices, (list, tuple)):
                errors['extra_params'].append(pgettext('error_msg', 'Field `choices` should be iterable'))
            else:
                for item in choices:
                    if not isinstance(item, str):
                        errors['extra_params'].append(
                            pgettext(
                                'error_msg', '{item}: Field `choices` should consist of strings',
                            ).format(item=item),
                        )
            self.extra_params['search_support'] = search
            self.extra_params['choices'] = choices

        if set(self.extra_params) - set(available):
            errors['extra_params'].append(
                pgettext(
                    'error_msg', 'Incorrect value provided: {incorrect_values}. Valid choices are: {available}',
                ).format(available=available, incorrect_values=set(self.extra_params) - set(available)),
            )
        if errors:
            raise ValidationError(errors)


class ParameterValue(AbstractTimestampModel):
    parameter = models.EmbeddedModelField(model_container=Parameter, verbose_name=pgettext_lazy('model_field', 'Parameter'))
    value = models.CharField(max_length=100, verbose_name=pgettext_lazy('model_field', 'Value'))

    class Meta:
        abstract = True

    @property
    def get_wrapped_value(self):
        value = self.value
        if value is not None:
            if self.parameter.field_type == Parameter.PARAMETER_TYPE_MULTISTRING:
                value = '<pre>{value}</pre>'.format(value=value)
            elif self.parameter.field_type == Parameter.PARAMETER_TYPE_DATETIME:
                value = datetime.datetime.strptime(value, '%Y-%m-%d %H:%i:%s').strftime('%m.%d.%Y %H:%i:%s')
            elif self.parameter.field_type == Parameter.PARAMETER_TYPE_DATE:
                value = datetime.datetime.strptime(value, '%Y-%m-%d').strftime('%m.%d.%Y')
            elif self.parameter.field_type == Parameter.PARAMETER_TYPE_SELECT:
                value = dict(utils.generate_choices(self.parameter.extra_params['choices'])).get(value)
            elif self.parameter.field_type == Parameter.PARAMETER_TYPE_SELECT_MULTIPLE:
                value = ', '.join(
                    [
                        dict(utils.generate_choices(self.parameter.extra_params['choices'])).get(value)
                        for value in ast.literal_eval(value)
                    ]
                )
        return value

    def __str__(self):
        return '{obj.parameter.name}={obj.value}'.format(obj=self)


class Project(AbstractTimestampModel):
    name = models.CharField(max_length=30, verbose_name=pgettext_lazy('model_field', 'Name'))
    code = models.CharField(max_length=CODE_MAX_LENGTH, verbose_name=pgettext_lazy('model_field', 'Code'))

    class Meta:
        verbose_name = pgettext_lazy('model_name', 'Project')
        verbose_name_plural = pgettext_lazy('model_name', 'Projects')

    def __str__(self):
        return self.name


class Form(AbstractTimestampModel):
    name = models.CharField(max_length=30, verbose_name=pgettext_lazy('model_field', 'Name'))
    # fields = models.ArrayReferenceField(to='hospital.Parameter', null=True, blank=True, verbose_name=pgettext_lazy('model_field', 'Fields'))
    fields = models.ManyToManyField(to='hospital.Parameter', related_name='parameter', verbose_name=pgettext_lazy('model_field', 'Fields'))
    project = models.ForeignKey(to='hospital.Project', on_delete=models.CASCADE, verbose_name=pgettext_lazy('model_field', 'Project'))
    code = models.CharField(max_length=CODE_MAX_LENGTH, verbose_name=pgettext_lazy('model_field', 'Code'))

    class Meta:
        verbose_name = pgettext_lazy('model_name', 'Form')
        verbose_name_plural = pgettext_lazy('model_name', 'Forms')

    def form_fields(self):
        fields = [field.name for field in self.fields.all()]
        return ', '.join(fields)

    def __str__(self):
        return self.name


class Application(AbstractTimestampModel):
    doctor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name=pgettext_lazy('model_field', 'Doctor'))
    patient = models.ForeignKey('hospital.Patient', on_delete=models.CASCADE, verbose_name=pgettext_lazy('model_field', 'Patient'))
    form = models.ForeignKey('hospital.Form', on_delete=models.CASCADE, verbose_name=pgettext_lazy('model_field', 'Form'))
    values = models.ArrayModelField(model_container=ParameterValue, verbose_name=pgettext_lazy('model_field', 'Values'))
    is_active = models.BooleanField(default=True, verbose_name=pgettext_lazy('model_field', 'Active'))
    parent = models.ForeignKey('hospital.Application', on_delete=models.CASCADE, verbose_name=pgettext_lazy('model_field', 'Parent'))

    class Meta:
        verbose_name = pgettext_lazy('model_name', 'Application')
        verbose_name_plural = pgettext_lazy('model_name', 'Applications')
        permissions = (
            ('manage_application', 'Can manage applications'),
            ('supervise_application', 'Can supervise applications per project'),
        )

    def __str__(self):
        return '{obj.form.project.code}:{obj.form.code}:{obj.values}'.format(obj=self)


# user extension models
class UserProfile(AbstractTimestampModel):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name=pgettext_lazy('model_field', 'User'))

hospital/forms.py
from django.forms import modelformset_factory

from . import models as hospital_models


ParameterFormSet = modelformset_factory(hospital_models.Parameter, fields=('name', 'description'), can_delete=True)
PatientFormSet = modelformset_factory(hospital_models.Patient, fields=('full_name', 'birthday',), can_delete=True)
ProjectFormSet = modelformset_factory(hospital_models.Project, fields=('name',), can_delete=True)
FormFormSet = modelformset_factory(hospital_models.Form, fields=('name',), can_delete=True)
ApplicationFormSet = modelformset_factory(hospital_models.Application, fields=('form', 'doctor', 'patient'), can_delete=True)

hospital/views/applications.py
from django.urls import reverse_lazy
from django.shortcuts import render
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from .. import forms as hospital_forms, models as hospital_models


def manage_applications(request):
    if request.method == 'POST':
        formset = hospital_forms.ApplicationFormSet(request.POST, request.FILES)
        if formset.is_valid():
            formset.save()
            formset = hospital_forms.ApplicationFormSet()
    else:
        formset = hospital_forms.ApplicationFormSet()
    return render(request, 'hospital/base_formset.html', {'formset': formset})


class ApplicationList(ListView):
    model = hospital_models.Application


class ApplicationCreate(CreateView):
    model = hospital_models.Application
    success_url = reverse_lazy('application-list')
    fields = ('name',)


class ApplicationUpdate(UpdateView):
    model = hospital_models.Application
    success_url = reverse_lazy('application-list')
    fields = ('name',)


class ApplicationDelete(DeleteView):
    model = hospital_models.Application
    success_url = reverse_lazy('application-list')

hospital/views/errors.py
from django.shortcuts import render
from django.utils.translation import pgettext_lazy


def permission_denied(request, exception):
    return render(
        request=request,
        template_name='hospital/error.html',
        context={
            'error_num': 403,
            'error_text': pgettext_lazy('error_msg', 'Forbidden'),
        },
    )

hospital/views/home.py
from django.shortcuts import render
from django.views import View

from .. import models as hospital_models


class HomeView(View):
    template_name = 'home/index.html'

    def get(self, request, *args, **kwargs):
        projects = hospital_models.Project.objects.all()
        return render(request, self.template_name, {'projects': projects})

hospital/views/profile.py
from django.shortcuts import render


def get_profile(request):
    return render(request, 'home/profile.html')

hospital/templates/hospital/base_formset.html
{% extends 'home/body.html' %}

{% block content %}
    <form method="post" action="">
      {{ formset.management_form }}
      {% for form in formset %}
          <div>
              {{ form }}
          </div>
      {% endfor %}
      <button type="submit">{% trans "Apply" context "action" %}</button>
    </form>
{% endblock %}

hospital/templates/hospital/error.html
{% extends 'home/body.html' %}

{% block content %}
<div class="text-center" style="width: 100%">
  <h1>{{ error_num }}</h1><h2>{{ error_text }}</h2>
</div>
{% endblock %}

hospital/templates/hospital/form_form.html
{% extends 'home/body.html' %}

{% block content %}
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="{% trans "Add" context "action" %}" />
    </form>
{% endblock %}

hospital/templates/hospital/form_list.html
{% extends 'home/body.html' %}

{% block content %}
    <h1>{{ view.model.model_name }}</h1>
    <ul>
        {% for object in object_list %}
        <li>
            <a href="{% url "form-update" object.id %}">{{ object.name }}</a>
            <a href="{% url "form-delete" object.id %}">{% trans "Delete" context "action" s%}</a>
        </li>
        {% endfor %}
    </ul>

    <a href="{% url "form-create" %}">{% trans "Add" context "action" s%}</a>
{% endblock %}

hospital/templates/hospital/history_and_form.html
{% extends 'home/body.html' %}

{% block content %}
  <form class="inline-form pull-left" action="{% url 'update_data' %}" method="POST">
    <div class="input-group mb-2 mr-sm-2">
      <div class="input-group-text">
        <i class="fa fa-fw fa-address-card"></i>
      </div>
      {{ patient_form.patient }}
    </div>
  </form>
  {% if perms.hospital.add_application %}
  <form class="inline-form pull-left" action="{% url 'update_data' %}" method="POST">
    <div class="input-group mb-2 mr-sm-2">
      <div class="input-group-text">
        <i class="fa fa-fw fa-wpforms"></i>
      </div>
      {{ patient_form.form }}
    </div>
  </form>
  {% endif %}
  <div style="clear:both;"></div>
  <ul class="nav nav-tabs" id="history_and_new_form_id">
    <li class="nav-item">
      <a class="nav-link active show" id="history_id" data-toggle="tab" href="#history" role="tab" aria-controls="history" aria-selected="true">{% trans "History" %}</a>
    </li>
    {% if perms.hospital.add_application %}
    <li class="nav-item">
      <a class="nav-link" id="new_form_id" data-toggle="tab" href="#new_form" role="tab" aria-controls="new-form" aria-selected="true">{% trans "New Application" %}</a>
    </li>
    {% endif %}
  </ul>
  <div class="tab-content" id="historyAndFormTabContent">
    <div class="tab-pane fade show active" id="history" role="tabpanel" aria-labelledby="history-tab">
      {% if request.session.patient %}
      <div class="table-responsive" style="margin: 20px 0;">
        <table class="table cell-border order-column" id="patientHistoryTable" width="100%" cellspacing="0">
          <thead>
              {% if perms.hospital.supervise_application %}
              <th class="patientHistoryCol_Doctor">{% trans 'Doctor' context "model_name" %}</th>
              {% endif %}
              <th class="patientHistoryCol_Form">{% trans "Form" context "model_name" %}</th>
              <th>{% trans "Applications" context "model_name" %}</th>
              <th class="patientHistoryCol_Date">{% trans "Added" context "model_field" %}</th>
            </tr>
          </thead>
          <tbody>
          {% for history in history_list %}
            <tr>
              {% if perms.hospital.supervise_application %}
              <td>{{ history.doctor.get_full_name }}</td>
              {% endif %}
              <td>{{ history.form.code }}</td>
              <td>
                {% for value in history.values %}
                {% autoescape off %}
                <b>{{ value.parameter }}</b>: {{ value.get_wrapped_value|default_if_none:"" }}
                {% if forloop.last %}{% else %}<br/>{% endif %}
                {% endautoescape %}
                {% endfor %}
              </td>
              <td>{{ history.created_at | date:"d.m.Y H:i:s" }}</td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
     {% else %}
      <div style="margin: 20px 0;">
        {% trans "Select patient to see the history" as select_patient context 'action' %}
        {% bootstrap_alert select_patient alert_type='info' dismissable=False %}
      </div>
      {% endif %}
    </div>
    <div class="tab-pane fade" id="new_form" role="tabpanel" aria-labelledby="new-form-tab">
      {% if form_to_fill %}
        <form method="POST" style="margin-top: 20px; margin-bottom: 20px;">
          {% bootstrap_form form_to_fill layout='inline' %}
          <button type="submit" class="btn btn-primary">{% trans 'Add' context 'action' %}</button>
        </form>
      {% else %}
       <div style="margin: 20px 0;">
         {% trans "Select patient and form to create new application" as select_patient_and_form %}
         {% bootstrap_alert select_patient_and_form alert_type='info' dismissable=False %}
       </div>
      {% endif %}
    </div>
  </div>
{% endblock %}

hospital/templates/hospital/parameter_confirm_delete.html
{% extends 'home/body.html' %}

{% block content %}
    <form method="post">{% csrf_token %}
        Are you sure you want to delete "{{ object }}" ?
        <input type="submit" value="{% trans "Delete" context "action" %}" />
    </form>
{% endblock %}

hospital/templates/hospital/parameter_form.html
{% extends 'home/body.html' %}

{% block content %}
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="{% trans "Apply" context "action" s%}" />
    </form>
{% endblock %}

hospital/templates/hospital/parameter_list.html
{% extends 'home/body.html' %}

{% block content %}
    <h1>{{ view.model.model_name }}</h1>
    <ul>
        {% for object in object_list %}
        <li>
            <a href="{% url "parameter-update" object.id %}">{{ object.name }}</a>
            <a href="{% url "parameter-delete" object.id %}">{% trans "Delete" context "action" %}</a>
        </li>
        {% endfor %}
    </ul>

    <a href="{% url "parameter-create" %}">{% trans "Add" context "action" %}</a>
{% endblock %}

hospital/templates/hospital/patient_confirm_delete.html
{% extends 'home/body.html' %}

{% block content %}
    <form method="post">{% csrf_token %}
        Are you sure you want to delete "{{ object }}" ?
        <input type="submit" value="{% trans "Delete" context "action"  %}" />
    </form>
{% endblock %}

hospital/templates/hospital/patient_form.html
{% extends 'home/body.html' %}

{% block content %}
  <form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button type="submit" class="btn btn-primary">{% trans 'Add' context "action" %}</button>
  </form>
{% endblock %}

hospital/templates/hospital/patient_list.html
{% extends 'home/body.html' %}

{% block content %}
    <h1>{{ view.model.model_name }}</h1>
    <ul>
        {% for object in object_list %}
        <li>
            <a href="{% url "patient-update" object.id %}">{{ object.full_name }}</a>
            <a href="{% url "patient-delete" object.id %}">{% trans "Delete" context "action" %}</a>
        </li>
        {% endfor %}
    </ul>

    <a href="{% url "patient-create" %}">{% trans "Add" context "action" %}</a>
{% endblock %}

hospital/templates/hospital/project_confirm_delete.html
{% extends 'home/body.html' %}

{% block content %}
    <form method="post">{% csrf_token %}
        Are you sure you want to delete "{{ object }}" ?
        <input type="submit" value="{% trans "Delete" context "action" %}" />
    </form>
{% endblock %}

hospital/templates/hospital/project_form.html
{% extends 'home/body.html' %}

{% block content %}
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="{% trans "Add" context "action" %}" />
    </form>
{% endblock %}

hospital/templates/hospital/project_list.html
{% extends 'home/body.html' %}

{% block content %}
    <h1>{{ view.model.model_name }}</h1>
    <ul>
        {% for object in object_list %}
        <li>
            <a href="{% url "project-update" object.id %}">{{ object.name }}</a>
            <a href="{% url "project-delete" object.id %}">{% trans "Delete" context "action" %}</a>
        </li>
        {% endfor %}
    </ul>

    <a href="{% url "project-create" %}">{% trans "Add" context "action" %}</a>
{% endblock %}